name: Run Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: install cpal dependencies
        run: sudo apt-get install libasound2-dev
      - name: run tests (desktop - all features)
        run: cargo test -p kira --all-features
      - name: run tests (desktop - no features)
        run: cargo test -p kira --no-default-features --lib
      - name: run tests (desktop - with cpal feature)
        run: cargo test -p kira --no-default-features --features=cpal --lib
      - name: run tests (desktop - with mp3 feature)
        run: cargo test -p kira --no-default-features --features=mp3 --lib
